<a href="https://colab.research.google.com/github/StefanTesmanovic/LSImprovement/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
def get_sentences_from_file(filename):
    sentences = []

    with open(filename, 'r') as file:
        text = file.read()
        sentences = text.split('.')
        sentences = [sentence.strip() for sentence in sentences if sentence.strip() != '']

    return sentences

file_name = "crnamacka.txt"
sentence_list = get_sentences_from_file(file_name)



In [52]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
corpus = [
     'This is the first document',
     'This document is the second document.',
     'And this is the third one',
     'Is this the first document?',
 ]
X = vectorizer.fit_transform(get_sentences_from_file(file_name))
#X = vectorizer.fit_transform(corpus)
print(X.toarray())
vectorizer.get_feature_names_out()
X = X.toarray()
print(X.shape)
vectorizer.get_feature_names_out()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(176, 1382)


array(['164', '165', '166', ..., 'zrelo', 'zvala', 'zvonak'], dtype=object)

In [56]:
import numpy as np
U, S, Vt = np.linalg.svd(np.transpose(X))
print(U.shape,"\n")
print(S,"\n")
print(Vt.shape)

(1382, 1382) 

[25.21103804 12.68475965 10.92284696 10.742727    9.87783682  9.2873359
  8.91533986  8.40487451  7.98432336  7.94076856  7.45604032  7.36340674
  7.31846598  7.04420229  6.91154922  6.73619756  6.60432529  6.55794023
  6.36635743  6.29376416  6.15309004  5.94921874  5.89406426  5.83789364
  5.78090249  5.68717107  5.60484577  5.59444034  5.44691803  5.38484029
  5.30287517  5.24682809  5.2158967   5.16776863  5.06735724  5.01429082
  5.00241578  4.95730347  4.92249294  4.86349306  4.83615067  4.789975
  4.73421438  4.68079713  4.64849138  4.59397491  4.54073692  4.52371302
  4.44943892  4.41248637  4.39294647  4.37791437  4.33038388  4.27658725
  4.23127985  4.22155863  4.19480493  4.16569757  4.13651758  4.09813605
  4.08669415  4.03241963  4.0033878   3.95460652  3.93951734  3.92488572
  3.88608914  3.8648017   3.84527768  3.81408773  3.79828531  3.7600025
  3.71434679  3.70384051  3.6864001   3.66556424  3.64373173  3.59485431
  3.57436255  3.53805963  3.50715944  3.