<a href="https://colab.research.google.com/github/StefanTesmanovic/LSImprovement/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import re


In [3]:
def get_sentences_from_file(filename):
    sentences = []

    with open(filename, 'r') as file:
        text = file.read()
        pattern = r'\.{3}\n|\.{3}|\.\n|\. |[!] |[?] |[!]+\n|[?]+\n'
        sentences = re.split(pattern, text)
        #sentences = [senten for sentence in sentences]
        print(sentences)
        print(type(sentences))
    return sentences


In [ ]:
def tfidf(text):

    terms = set([])




In [4]:
def remove_zero_columns(X):
    # Find indices of columns with all zeros
    non_zero_columns = np.any(X != 0, axis=0)

    # Create a new matrix without columns of all zeros
    return X[:, non_zero_columns]


In [4]:
def tf(X):
    col_sums = np.sum(X, axis=0)
    return X/col_sums

In [5]:
def idf(X):
    sent_count = X.shape[1]
    return np.transpose(np.transpose(X)/row_sums)

In [6]:
corpus = [
     'Dobar dan',
     'Zasto ovo ne radi',
     'Jako je glupo',
     'Od jednom je prestalo da radi, mrzim ga.'
      ]
print(corpus)
print(type(corpus))
vectorizer = TfidfVectorizer()
file_name = "tekst.txt"
X = vectorizer.fit_transform(corpus)
X = vectorizer.fit_transform(get_sentences_from_file(file_name))
X = X.toarray()
X = np.transpose(X)
print(X)
X = remove_zero_columns(X)
print(X.shape)
vectorizer.get_feature_names_out()

['Dobar dan', 'Zasto ovo ne radi', 'Jako je glupo', 'Od jednom je prestalo da radi, mrzim ga.']
<class 'list'>
['Dobar dan', 'Zasto ovo ne d.t radi', 'Jako je glupo', ' Od jednom je prestalo da radi, mrzim ga.']
<class 'list'>
[[0.         0.         0.         0.37156534]
 [0.70710678 0.         0.         0.        ]
 [0.70710678 0.         0.         0.        ]
 [0.         0.         0.         0.37156534]
 [0.         0.         0.61761437 0.        ]
 [0.         0.         0.61761437 0.        ]
 [0.         0.         0.48693426 0.29294639]
 [0.         0.         0.         0.37156534]
 [0.         0.         0.         0.37156534]
 [0.         0.52547275 0.         0.        ]
 [0.         0.         0.         0.37156534]
 [0.         0.52547275 0.         0.        ]
 [0.         0.         0.         0.37156534]
 [0.         0.41428875 0.         0.29294639]
 [0.         0.52547275 0.         0.        ]]
(15, 4)


array(['da', 'dan', 'dobar', 'ga', 'glupo', 'jako', 'je', 'jednom',
       'mrzim', 'ne', 'od', 'ovo', 'prestalo', 'radi', 'zasto'],
      dtype=object)

In [ ]:
import math
from collections import Counter

# Sample documents
documents = [
    "This is the first document.",
    "This document is the second document.",
    "And this is the third one.",
    "Is this the first document?"
]

# Tokenize and count term frequencies
tf_documents = [Counter(doc.lower().split()) for doc in documents]

# Calculate total number of documents
total_documents = len(documents)

# Calculate document frequencies
df = {}
for tf_doc in tf_documents:
    for term in tf_doc:
        df[term] = df.get(term, 0) + 1

# Calculate inverse document frequencies
idf = {term: math.log(total_documents / df[term]) for term in df}

# Calculate TF-IDF values
tfidf_documents = []
for tf_doc in tf_documents:
    tfidf_doc = {term: tf * idf[term] for term, tf in tf_doc.items()}
    tfidf_documents.append(tfidf_doc)

# Print TF-IDF values for each document
for idx, tfidf_doc in enumerate(tfidf_documents):
    print(f"TF-IDF values for Document {idx + 1}:")
    for term, tfidf in tfidf_doc.items():
        print(f"{term}: {tfidf}")
    print()


In [39]:
X_norm = norm(X)
X_tfidf = tfidf(X)
U, S, Vt = np.linalg.svd(X)
'''print(U.shape,"\n")
print(S.shape,"\n")
print(Vt.shape)'''

'print(U.shape,"\n")\nprint(S.shape,"\n")\nprint(Vt.shape)'

In [28]:
def reduce(U, S, Vt, l):
    sum = np.sum(S)
    for i in range(int(len(S)/2), len(S)):
      if(np.sum(S[:i])/sum >= l):#ulazi ako prvih i vrednosti zadovoljava nejdnakost
        print(i)
        return (np.delete(U,np.s_[i:],1), S[:i], np.delete(Vt, np.s_[i:], 0))
        break



In [32]:
def WW(U, S):
  return (U * S**2) @ np.transpose(U)

In [ ]:
def SS(Vt, S):
    return (np.transpose(Vt) * S**2) @ Vt

In [ ]:
def depth(ss):


In [30]:
def LSI(U, S, Vt):
    (U, S, Vt) = reduce(U, S, Vt, 0.975)
    ww = WW(U, S)
    ss = SS(Vt, S)
